#!/usr/bin/env bash

## Copyright (C) 2024 Italo Maia <itin.bmx@hotmail.com>

# i3 directory
DIR="$HOME/.config/i3"

# rofi sudo askpass helper
export SUDO_ASKPASS="$DIR"/scripts/rofi_askpass

# execute the application
sudo -A $1
