#!/usr/bin/env bash

## Copyright (C) 2024 Italo Maia <itin.bmx@hotmail.com>
##
## Run ncmpcpp with alternate config

# i3 directory
DIR="$HOME/.config/i3"

CONFIG="$DIR/alacritty/alacritty.toml"

alacritty --class 'Music,Music' --config-file "$CONFIG" \
		  -o window.dimensions.columns=105 window.dimensions.lines=22 \
		  -e ~/.ncmpcpp/scripts/ncmpcpp-art
