#!/usr/bin/env bash

## Copyright (C) 2024 Italo Maia <itin.bmx@hotmail.com>

# Import Current Theme
DIR="$HOME/.config/i3"
RASI="$DIR/theme/rofi/askpass.rasi"

# Rofi text dialog to get password
rofi -dmenu \
     -password \
     -i \
     -p "Root" \
     -theme ${RASI}
