#!/usr/bin/env bash

## Copyright (C) 2024 Italo Maia <itin.bmx@hotmail.com>

# Import Current Theme
DIR="$HOME/.config/i3"
RASI="$DIR/theme/rofi/runner.rasi"

# Run
rofi \
    -show run \
	-theme ${RASI}
